on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: 0.28.2

      - run: APIKEY="${{ secrets.API_KEY }}" pkl eval -f yaml config.pkl > config.yaml

      - name: Deploy infrastructure
        uses: kaihendry/actions/terraform@main # The custom action
        with:
          # Input for the custom action: path to the config file
          config-file: 'config.yaml'
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
