on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy infrastructure
        uses: kaihendry/actions/terraform@main # The custom action
        with:
          tf-api-token: ${{ secrets.TF_API_TOKEN }}
        env:
          APIKEY: ${{ secrets.APIKEY }}
