on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy infrastructure
        uses: kaihendry/actions/terraform@main # The custom action
        with:
          # Input for the custom action: path to the config file
          config-file: 'config.yaml'

          # Input for the custom action: the secret value
          api-key: ${{ secrets.API_KEY }}
